Add convenience function for check key path values
rosberry/Rosberry-Generamba-Templates pull request #4
Opened 2020-04-02 13:19 UTC by artemnovichkov

Here is an example of using

BEFORE
```swift
func update(with viewModel: SearchViewModel, force: Bool, animated: Bool) {
        let oldViewModel = self.viewModel
        self.viewModel = viewModel

        collectionViewManager.update(with: viewModel.listSectionItems, animated: animated)

        update(new: viewModel, old: oldViewModel, keyPath: \.isPlaceholderHidden, force: force) { isHidden in
            placeholderView.setHidden(isHidden, animated: animated)
        }

        update(new: viewModel, old: oldViewModel, keyPath: \.placeholderViewModel, force: force) { placeholderViewModel in
            placeholderView.update(with: placeholderViewModel, force: force, animated: animated)
        }

        update(new: viewModel, old: oldViewModel, keyPath: \.isPlaceholderActionHidden, force: force) { isHidden in
            placeholderActionView.setHidden(isHidden, animated: animated)
        }

        update(new: viewModel, old: oldViewModel, keyPath: \.placeholderActionViewModel, force: force) { placeholderViewModel in
            placeholderActionView.update(with: placeholderViewModel, force: force, animated: animated)
        }

        update(new: viewModel, old: oldViewModel, keyPath: \.isLoaderHidden, force: force) { isHidden in
            loaderView.setHidden(isHidden, animated: animated)
        }

        update(new: viewModel, old: oldViewModel, keyPath: \.loaderViewModel, force: force) { loaderViewModel in
            loaderView.update(with: loaderViewModel, force: force, animated: animated)
        }
    }
```

AFTER
```swift
func update(with viewModel: SearchViewModel, force: Bool, animated: Bool) {
        let oldViewModel = self.viewModel
        self.viewModel = viewModel

       func updateViewModel<Value: Equatable>(_ keyPath: KeyPath<SearchViewModel, Value>, configurationBlock: (Value) -> Void) {
            update(new: viewModel, old: oldViewModel, keyPath: keyPath, force: force, configurationBlock: configurationBlock)
        }

        collectionViewManager.update(with: viewModel.listSectionItems, animated: animated)

        updateViewModel(\.isPlaceholderHidden) { isHidden in
            placeholderView.setHidden(isHidden, animated: animated)
        }

        updateViewModel(\.placeholderViewModel) { placeholderViewModel in
            placeholderView.update(with: placeholderViewModel, force: force, animated: animated)
        }

        updateViewModel(\.isPlaceholderActionHidden) { isHidden in
            placeholderActionView.setHidden(isHidden, animated: animated)
        }

        updateViewModel(\.placeholderActionViewModel) { placeholderViewModel in
            placeholderActionView.update(with: placeholderViewModel, force: force, animated: animated)
        }

        updateViewModel(\.isLoaderHidden) { isHidden in
            loaderView.setHidden(isHidden, animated: animated)
        }

        updateViewModel(\.loaderViewModel) { loaderViewModel in
            loaderView.update(with: loaderViewModel, force: force, animated: animated)
        }
    }
```

2020-04-03 10:29 UTC, zhvrnkov commented on rsb_mvp_vm_list_module/Code/ViewController.swift.liquid
> +        func updateViewModel<Value: Equatable>(_ keyPath: KeyPath<SearchViewModel, Value>, configurationBlock: (Value) -> Void) {
Isn't it `{{ module_info.name }}ViewModel`?

2020-04-03 10:47 UTC, stason314 approved these changes
😍

2020-05-15 07:30 UTC, ntunin requested changes

2020-05-15 07:30 UTC, ntunin commented on rsb_mvp_vm_list_module/Code/ViewController.swift.liquid
> +        func updateViewModel<Value: Equatable>(_ keyPath: KeyPath<SearchViewModel, Value>, configurationBlock: (Value) -> Void) {
Yep. `SearchViewModel ` looks like hardcode

2020-05-15 07:30 UTC, ntunin commented on rsb_mvp_vm_module/Code/ViewController.swift.liquid
> +        func updateViewModel<Value: Equatable>(_ keyPath: KeyPath<SearchViewModel, Value>, configurationBlock: (Value) -> Void) {
same here

2020-06-04 10:15 UTC, ntunin approved these changes

2020-06-05 03:01 UTC, merged